// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP0bNjlUFU38F5HLWqJARdtrUWyc7R3gg',
    appId: '1:183199730954:web:a169a64cda908c51383ef3',
    messagingSenderId: '183199730954',
    projectId: 'ahla-live',
    authDomain: 'ahla-live.firebaseapp.com',
    databaseURL: 'https://ahla-live-default-rtdb.firebaseio.com',
    storageBucket: 'ahla-live.firebasestorage.app',
    measurementId: 'G-ZYK2BGX5X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeRauEkyFcsB7ryTYTx28aOO2szSBZjCg',
    appId: '1:183199730954:android:cbf937664eb5f2fd383ef3',
    messagingSenderId: '183199730954',
    projectId: 'ahla-live',
    databaseURL: 'https://ahla-live-default-rtdb.firebaseio.com',
    storageBucket: 'ahla-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeRauEkyFcsB7ryTYTx28aOO2szSBZjCg',
    appId: '1:183199730954:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '183199730954',
    projectId: 'ahla-live',
    storageBucket: 'ahla-live.firebasestorage.app',
    iosBundleId: 'com.ahlalive.app',
  );
}
